openapi: 3.0.3

info :
  title: payments API
  version : 1.0.1
  contact:
    name: Sachin
    url: sachin.vishwa.in
    email: sachin@gmail.com
  
servers:
  - url: http://127.0.0.1:5000
    description: DEV Server
    
  - url: https://127.0.0.1:6000
    description: UAT Server
    
  - url: https://127.0.0.1:7090
    description: PRE PROD Server
   

paths : 
  /apiStatus:
    get:
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string  
                  date:
                    type: string  
                  time:
                    type: string  
              examples:
                api-status-example:
                  value:
                    message: API is up!
        '404':
          description: page not found
  
  /payments: 
    post:
      responses:
        '200':
          description: Transaction is created
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: string
                  transaction_id:
                    type: string
                  payer_upi:
                    type: string
                  payee_upi:
                    type: string
                  status:
                    type: string
                  timestamp:
                    type: string
              examples:
                txn_1:
                  value:
                    "amount": 130
                    "note": "Books"
                    "payee_upi": "qwe-sbi"
                    "payer_upi": "abx@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 23 Jul 2024 14:16:27 GMT"
                    "transaction_id": "8040cb86-04a2-492b-9b0a-c1b3a450c509"
                txn_2:
                  value:
                    "amount": 300
                    "note": "Ola"
                    "payee_upi": "krish@icici"
                    "payer_upi": "abx@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 27 Jul 2024 12:45:27 GMT"
                    "transaction_id": "a5560f7c-123c-46bc-a93f-9ca1ede78957"
                txn_3:
                  value:
                    "amount": 500
                    "note": "Rent"
                    "payee_upi": "abc@okicici"
                    "payer_upi": "xyz@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 31 Jul 2024 12:45:27 GMT"
                    "transaction_id": "30bf4f62-69bd-427a-8974-f2881a061a2b"  
                        
                    
    
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                  minimum: 0
                  maximum: 1000
                 
                payer_upi:
                  type: string
                payee_upi:
                  type: string
                
                note:
                  type: string
                  
              required:
                - amount
                - payee_upi
                - payer_upi
            examples:
                txn_with_note:
                  value:
                    "amount": 130
                    "note": "Books"
                    "payee_upi": "qwe-sbi"
                    "payer_upi": "abx@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 23 Jul 2024 14:16:27 GMT"
                    "transaction_id": "8040cb86-04a2-492b-9b0a-c1b3a450c509"
                txn_without_note:
                  value:
                    "amount": 300
                    "note": "Ola"
                    "payee_upi": "krish@icici"
                    "payer_upi": "abx@okhdfc"
                    "status": "failed"
                    "timestamp": "Tue, 27 Jul 2024 12:45:27 GMT"
                    "transaction_id": "a5560f7c-123c-46bc-a93f-9ca1ede78957"
               
                    
  
  
                    
  /payments/{transaction_id}:
    put:
      description: Updating a transaction by transaction ID
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  minimum: 0
                  maximum: 100000
                payer_upi:
                  type: string
                payee_upi:
                  type: string
                note:
                  type: string
          
      responses:
        '200':
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: integer
                  payer_upi:
                    type: string
                  payee_upi:
                    type: string
                  note:
                    type: string
                  status:
                    type: string
                  timestamp:
                    type: string
                  transaction_id:
                    type: string
  
    delete:
      description: TO delete a transaction
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: string
          
      responses:
        '204':
          description: Payment initiated successfully
          
    
    get:
      description: TO delete a transaction
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: integer
                  payer_upi:
                    type: string
                  payee_upi:
                    type: string
                  note:
                    type: string
                  status:
                    type: string
                  timestamp:
                    type: string
                  transaction_id:
                    type: string
              examples:
                txn_with_status_initiated:
                  value:
                    "amount": 130
                    "note": "Books"
                    "payee_upi": "qwe-sbi"
                    "payer_upi": "abx@okhdfc"
                    "status": "initiated"
                    "timestamp": "Tue, 23 Jul 2024 14:16:27 GMT"
                    "transaction_id": "8040cb86-04a2-492b-9b0a-c1b3a450c509"
                txn_with_status_failed:
                  value:
                    "amount": 300
                    "note": "Ola"
                    "payee_upi": "krish@icici"
                    "payer_upi": "abx@okhdfc"
                    "status": "failed"
                    "timestamp": "Tue, 27 Jul 2024 12:45:27 GMT"
                    "transaction_id": "a5560f7c-123c-46bc-a93f-9ca1ede78957"
               
                  
      
            
  
        
      
        
  
  
  /signUp: {}
  